### ISSUE TITLE
Plugin does not working with higher GC version

### ISSUE THREAD

**Issue by FISHandCHEAP** [Penelopeep/ToggleConstellation#2]
Tested with GC 1.4.1 and Game 3.1, the plugin just does not work

**Comment by Penelopeep** [comment]
Ouch... that's never a good sign, I'll look into that

**Comment by Penelopeep** [comment]
![image](https://user-images.githubusercontent.com/81880849/197247780-2f888981-95f1-4c4e-9b27-558213709bf5.png)
I tried running it with Grasscutter 1.4.2-dev and it seems to work.
It's probably problem with your plugin/grasscutter installation, reach me out on discord Penelopeep#7963 and I'll try to help you with it
