### ISSUE TITLE
bugs with GC version 1.4.1

### ISSUE THREAD

**Issue by FISHandCHEAP** [Penelopeep/ToggleConstellation#3]
Hi, it's me again.

I didn't know that I have to activate a character's const before using the plugin's command, so I submitted issue #2 

But there are still bugs with the plugin.

Here's a case: 

for a new character with no const activated before, use command /tc 6, his 6th const remains unactivated. There's no bug so far.

Then use GC's command /setconst 6, which should activate all his const, only activated some of his const.

For different characters, how many const will be activated is different, but usually are 2th and 4th.

I don't know why this happened but it's definitely a bug, and I guess it is because the plugin clashes with GC's command somehow.

By the way, it would be more clear for new users if you can introduce the following two rules of the plugin in readme:

1. you have to activate a character's const before using plugin's command

2. /tc all can only turn const on and cannot turn them off

**Comment by FISHandCHEAP** [comment]
Forgot to mention that, the bug will bring some error information in Java's console, which I can't understand

**Comment by Penelopeep** [comment]
May I see this error? It'll help me a lot

**Comment by FISHandCHEAP** [comment]
> However in my case I also can't use setconst, it might be similiar issue. But I don't any error in console, maybe because I use 1.4.2-dev, I'll try it on 1.4.1. 

I guess you can't use /setconst because they redesigned the const-relevant commands on dev 1.4.2 as there are some bugs. You can use it on 1.4.1

> May I see this error? It'll help me a lot.
![2](https://user-images.githubusercontent.com/58490693/197399811-5680dddc-9f58-4cdb-a4eb-b924f014f9f5.png)

The above one is definitely caused by bugs related to the plugin. I used /tc 6 first and then /setconst 6. Only first 5 consts of the character is activated, and the error log shows.

![1](https://user-images.githubusercontent.com/58490693/197399932-3b04cdaa-de4d-407e-9c35-87d7ed2664d4.png)
I am not sure if the above one is caused by the installation of the plugin, because it shows right after I log in. Even if it's not, could you please tell me what's the problem? So maybe I can fix it somehow.

**Comment by Penelopeep** [comment]
> The above one is definitely caused by bugs related to the plugin. I used /tc 6 first and then /setconst 6. Only first 5 consts of the character is activated, and the error log shows.

I think I got fix for that one error.
And I almost got what's going on with this "C0 characters bug"... however I don't know how to fix it yet. 
Basically what's happening is server doesn't reconise that character have unlocked constellation, and what's even weirder is that C0 character have all constellation added from the beginning.
You can see this by using `/tg` on every constellation on C0 character, each time plugin will respond with "Constellation was deactivated".

 > I am not sure if the above one is caused by the installation of the plugin, because it shows right after I log in. Even if it's not, could you please tell me what's the problem? So maybe I can fix it somehow.
 
 This isn't caused by a plugin (or atleast it shouldn't since it's have nothing to do with mobs).

**Comment by FISHandCHEAP** [comment]
> I think I got fix for that one error.

That's good news, looking forward to your next release!

> This isn't caused by a plugin (or atleast it shouldn't since it's have nothing to do with mobs).

Then I guess that's the problem with the resource I use. Can I know where do you get your resources?

**Comment by Penelopeep** [comment]
> That's good news, looking forward to your next release!
You can download it now, however it's still weird since you need to use `/tc` twice to unlock C0 character constellation.
But you're welcome.
> Then I guess that's the problem with the resource I use. Can I know where do you get your resources?
I'm using official with some beta files
